# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
description="3 step form vs 4 step form"
campaign_tracking = "00-ba-230202"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/banner_ctrl.ts"
pagename = "B23WMDE_00_230202_ctrl"
tracking = "org-00-230202-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/banner_var.ts"
pagename = "B23WMDE_00_230202_var"
tracking = "org-00-230202-var"

# English Campaign
[english]
description="VAR has the already donated modal"
campaign_tracking = "en00-ba-230421"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype&devMode"
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[english.banners.ctrl]
filename = "./banners/english/banner_ctrl.ts"
pagename = "B23_WMDE_Test_EN_00_ctrl"
tracking = "org-en00-230421-ctrl"

[english.banners.var]
filename = "./banners/english/banner_var.ts"
pagename = "B23_WMDE_Test_EN_00_var"
tracking = "org-en00-230421-var"

[mobile]
description="2 step form vs 3 step form"
campaign_tracking = "00-ba-230202"
preview_link = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva"
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[mobile.banners.ctrl]
filename = "./banners/mobile/banner_ctrl.ts"
pagename = "B23WMDE_00_Mobile_230202_ctrl"
tracking = "org-00-230202-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/banner_var.ts"
pagename = "B23WMDE_00_Mobile_230202_var"
tracking = "org-00-230202-var"

# Mobile English Campaign
[mobile_english]
description="Tab button VS interior button on mini banners"
campaign_tracking = "mob_en00-ba-230425"
preview_link = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype&devMode"
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}'
wrapper_template = "wikipedia_org"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/banner_ctrl.ts"
pagename = "B23_WMDE_Mobile_EN_Test_00_ctrl"
tracking = "org-mob_en00-230425-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/banner_var.ts"
pagename = "B23_WMDE_Mobile_EN_Test_00_var"
tracking = "org-mob_en00-230425-var"

# desktop banners on wikipedia.de
[wikipediade]
name = "C23_WPDE_00"
description="Nothing to see here"
campaign_tracking = "wpde-00-230202"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade.banners.ctrl]
filename = "./banners/wpde_desktop/banner_ctrl.ts"
pagename = "B23WPDE_00_ctrl"
tracking = "wpde-00-230202-ctrl"

# iPad campaign
[pad]
name = "iPad Test 00"
description="VAR has a header text above the slider"
campaign_tracking = "pad00-ba-230426"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&devMode"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
wrapper_template = "wikipedia_org"

[pad.banners.ctrl]
filename = "./banners/pad/banner_ctrl.ts"
pagename = "B23_WMDE_ipad_Test_00_ctrl"
tracking = "org-pad00-230426-ctrl"

[pad.banners.var]
filename = "./banners/pad/banner_var.ts"
pagename = "B23_WMDE_ipad_Test_00_var"
tracking = "org-pad00-230426-var"
# iPad English campaign
[pad_en]
name = "Pad_en"
campaign_tracking = "en-ipad01-230426"
preview_link ='/wiki/Main_Page?banner={{banner}}&devMode=true'
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{PLACEHOLDER}}'
wrapper_template = "wikipedia_org"

[pad_en.banners.ctrl]
filename = "./banners/pad_english/banner_ctrl.ts"
pagename = "B23_WMDE_ipad_en_01_ctrl"
tracking = "org-en-ipad01-230426-ctrl"
