# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
name = "Desktop"
icon = "desktop"
campaign = "C23_WMDE_Desktop_DE_25"
description = "based on VAR of test 24, VAR has minimse banner"
campaign_tracking = "25-ba-231227"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/banner_ctrl.ts"
pagename = "B23_WMDE_Desktop_DE_25_ctrl"
tracking = "org-25-231227-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/banner_var.ts"
pagename = "B23_WMDE_Desktop_DE_25_var"
tracking = "org-25-231227-var"

[desktop.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]


[mobile]
name = "Mobile"
icon = "mobile"
campaign = "C23_WMDE_Mobile_DE_14"
description = "based on VAR of 13, VAR has a text test"
campaign_tracking = "mob-de-14-ba-231222"
preview_link = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva"
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&useskin=minerva&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[mobile.banners.ctrl]
filename = "./banners/mobile/banner_ctrl.ts"
pagename = "B23_WMDE_Mobile_DE_14_ctrl"
tracking = "org-mob14-231222-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/banner_var.ts"
pagename = "B23_WMDE_Mobile_DE_14_var"
tracking = "org-mob14-231222-var"

[mobile.test_matrix]
device = [ 'samsung_s10', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max"]
orientation = [ "portrait", "landscape"]


[pad]
name = "iPad"
icon = "pad"
campaign = "C23_WMDE_iPad_01"
description = "VAR has payment logos"
campaign_tracking = "pad01-ba-231030"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

[pad.banners.ctrl]
filename = "./banners/pad/banner_ctrl.ts"
pagename = "B23_WMDE_iPad_01_ctrl"
tracking = "org-pad01-231030-ctrl"

[pad.banners.var]
filename = "./banners/pad/banner_var.ts"
pagename = "B23_WMDE_iPad_01_var"
tracking = "org-pad01-231030-var"

[pad.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch' ]
orientation = [ "portrait", "landscape"]



[wikipediade]
name = "WPDE Desktop"
icon = "desktop"
campaign = "C23_WPDE_Desktop_01"
description = "VAR has translated WMF copy"
campaign_tracking = "wpde-01-231030"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade.banners.ctrl]
filename = "./banners/wpde_desktop/banner_ctrl.ts"
pagename = "B23_WPDE_Desktop_01_ctrl"
tracking = "wpde-01-231030-ctrl"

[wikipediade.banners.var]
filename = "./banners/wpde_desktop/banner_var.ts"
pagename = "B23_WPDE_Desktop_01_var"
tracking = "wpde-01-231030-var"


[wikipediade_mobile]
name = "WPDE Mobile"
icon = "mobile"
campaign = "C23_WPDE_Mobile_01"
description = "Based on CRTL of WPDE_mob_01"
campaign_tracking = "wpde-mob01-231030"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade_mobile.banners.ctrl]
filename = "./banners/wpde_mobile/banner_ctrl.ts"
pagename = "B23_WPDE_Mobile_01_ctrl"
tracking = "wpde-mob01-231030-ctrl"

[wikipediade_mobile.banners.var]
filename = "./banners/wpde_mobile/banner_var.ts"
pagename = "B23_WPDE_Mobile_01_var"
tracking = "wpde-mob01-231030-var"



[english]
name = "English Desktop"
icon = "desktop"
campaign = "C23_WMDE_Desktop_EN_05"
description = "Based on VAR of 04, VAR has the direct redirect"
campaign_tracking = "en05-ba-231218"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[english.banners.ctrl]
filename = "./banners/english/banner_ctrl.ts"
pagename = "B23_WMDE_Desktop_EN_05_ctrl"
tracking = "org-en05-231218-ctrl"

[english.banners.var]
filename = "./banners/english/banner_var.ts"
pagename = "B23_WMDE_Desktop_EN_05_var"
tracking = "org-en05-231218-var"

[english.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]



[mobile_english]
name = "English Mobile"
icon = "mobile"
campaign = "C23_WMDE_Mobile_EN_02"
description = "var leads directly to payment provider page"
campaign_tracking = "mob_en02-ba-231206"
preview_link = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode&useskin=minerva'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/banner_ctrl.ts"
pagename = "B23_WMDE_Mobile_EN_02_ctrl"
tracking = "org-mob_en02-231206-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/banner_var.ts"
pagename = "B23_WMDE_Mobile_EN_02_var"
tracking = "org-mob_en02-231206-var"

[mobile_english.test_matrix]
device = [ 'samsung_s10', 'nexus_6', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max" ]
orientation = [ "portrait", "landscape" ]


[pad_en]
name = "English iPad"
icon = "pad"
campaign = "C23_WMDE_iPad_EN_00"
description = "VAR has soft close"
campaign_tracking = "en-ipad00-230426"
preview_link ='/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype'
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[pad_en.banners.ctrl]
filename = "./banners/pad_english/banner_ctrl.ts"
pagename = "B23_WMDE_iPad_EN_00_ctrl"
tracking = "org-en-ipad00-230501-ctrl"

[pad_en.banners.var]
filename = "./banners/pad_english/banner_var.ts"
pagename = "B23_WMDE_iPad_EN_00_var"
tracking = "org-en-ipad00-230501-var"

[pad_en.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch']
orientation = [ "portrait", "landscape"]
