# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
name = "Desktop"
icon = "desktop"
campaign = "C24_WMDE_Desktop_DE_05"
description = "Based on C24_WMDE_Desktop_DE_04_var, var: with an amount <= €10 leads to the default donation form (ap=0), with an amount > €10 leads to the variant donation form (ap=1)"
campaign_tracking = "05-ba-240913"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/C24_WMDE_Desktop_DE_05/banner_ctrl.ts"
pagename = "B24_WMDE_Desktop_DE_05_ctrl"
tracking = "org-05-240913-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/C24_WMDE_Desktop_DE_05/banner_var.ts"
pagename = "B24_WMDE_Desktop_DE_05_var"
tracking = "org-05-240913-var"

[desktop.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]


[mobile]
name = "Mobile"
icon = "mobile"
campaign = "C24_WMDE_Mobile_DE_04"
description = "Based on C24_WMDE_Mobile_DE_03 var, var: submitting the form with an amount equal to or above €10,01 leads to the variant donation form (ap=1), both banners: are reduced in height to approximately match mobile-de-06 from 2023 "
campaign_tracking = "mob-de-04-ba-240909"
preview_link = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva"
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&useskin=minerva&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

# Banners of the campaign, key after "banners" can be anything
[mobile.banners.ctrl]
filename = "./banners/mobile/C24_WMDE_Mobile_DE_04/banner_ctrl.ts"
pagename = "B24_WMDE_Mobile_DE_04_ctrl"
tracking = "org-mob04-240909-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/C24_WMDE_Mobile_DE_04/banner_var.ts"
pagename = "B24_WMDE_Mobile_DE_04_var"
tracking = "org-mob04-240909-var"

[mobile.test_matrix]
device = [ 'samsung_s10', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max"]
orientation = [ "portrait", "landscape"]


[pad]
name = "iPad"
icon = "pad"
campaign = "C24_WMDE_iPad_00"
description = "Based on C23_WMDE_iPad_01"
campaign_tracking = "pad00-ba-240619"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

[pad.banners.ctrl]
filename = "./banners/pad/C24_WMDE_iPad_00/banner_ctrl.ts"
pagename = "B24_WMDE_iPad_00_ctrl"
tracking = "org-pad00-240619-ctrl"

[pad.banners.var]
filename = "./banners/pad/C24_WMDE_iPad_00/banner_var.ts"
pagename = "B24_WMDE_iPad_00_var"
tracking = "org-pad00-240619-var"

[pad.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch' ]
orientation = [ "portrait", "landscape"]



[wikipediade]
name = "WPDE Desktop"
icon = "desktop"
campaign = "C24_WPDE_Desktop_00"
description = "Based on C23_WPDE_Desktop_01"
campaign_tracking = "wpde-00-240619"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade.banners.ctrl]
filename = "./banners/wpde_desktop/C24_WPDE_Desktop_00/banner_ctrl.ts"
pagename = "B24_WPDE_Desktop_00_ctrl"
tracking = "wpde-00-240619-ctrl"

[wikipediade.banners.var]
filename = "./banners/wpde_desktop/C24_WPDE_Desktop_00/banner_var.ts"
pagename = "B24_WPDE_Desktop_00_var"
tracking = "wpde-00-240619-var"


[wikipediade_mobile]
name = "WPDE Mobile"
icon = "mobile"
campaign = "C24_WPDE_Mobile_00"
description = "Based on C23_WPDE_Mobile_01"
campaign_tracking = "wpde-mob00-240619"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade_mobile.banners.ctrl]
filename = "./banners/wpde_mobile/C24_WPDE_Mobile_00/banner_ctrl.ts"
pagename = "B24_WPDE_Mobile_00_ctrl"
tracking = "wpde-mob00-240619-ctrl"

[wikipediade_mobile.banners.var]
filename = "./banners/wpde_mobile/C24_WPDE_Mobile_00/banner_var.ts"
pagename = "B24_WPDE_Mobile_00_var"
tracking = "wpde-mob00-240619-var"



[english]
name = "English Desktop"
icon = "desktop"
campaign = "C24_WMDE_Desktop_EN_01"
description = "Based on C23_WMDE_Desktop_EN_05"
campaign_tracking = "en01-ba-090324"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN"

[english.banners.ctrl]
filename = "./banners/english/C24_WMDE_Desktop_EN_01/banner_ctrl.ts"
pagename = "B24_WMDE_Desktop_EN_01_ctrl"
tracking = "org-en01-090324-ctrl"

[english.banners.var]
filename = "./banners/english/C24_WMDE_Desktop_EN_01/banner_var.ts"
pagename = "B24_WMDE_Desktop_EN_01_var"
tracking = "org-en01-090324-var"

[english.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]



[mobile_english]
name = "English Mobile"
icon = "mobile"
campaign = "C24_WMDE_Mobile_EN_00"
description = "Based on C23_WMDE_Mobile_EN_02"
campaign_tracking = "mob_en00-ba-240619"
preview_link = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode&useskin=minerva'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/C24_WMDE_Mobile_EN_00/banner_ctrl.ts"
pagename = "B24_WMDE_Mobile_EN_00_ctrl"
tracking = "org-mob_en00-240619-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/C24_WMDE_Mobile_EN_00/banner_var.ts"
pagename = "B24_WMDE_Mobile_EN_00_var"
tracking = "org-mob_en00-240619-var"

[mobile_english.test_matrix]
device = [ 'samsung_s10', 'nexus_6', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max" ]
orientation = [ "portrait", "landscape" ]

