# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
name = "Desktop"
icon = "desktop"
campaign = "C24_WMDE_Desktop_DE_14"
description = "Based on the CTRL banner of C24_WMDE_Desktop_DE_13, VAR adds additional copy, displays the '10 good reasons' overlay when the link in the added copy is clicked"
campaign_tracking = "14-ba-241119"
preview_link = "/wiki/Hamster?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Hamster?devbanner={{banner}}&banner=B22_WMDE_local_prototype&vectornightmode=1"
preview_url = 'https://de.wikipedia.org/wiki/Hamster?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/C24_WMDE_Desktop_DE_14_minimised/banner_ctrl.ts"
pagename = "B24_WMDE_Desktop_DE_14_ctrl"
tracking = "org-14-241119-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/C24_WMDE_Desktop_DE_14_minimised/banner_var.ts"
pagename = "B24_WMDE_Desktop_DE_14_var"
tracking = "org-14-241119-var"

[desktop.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]


[mobile]
name = "Mobile"
icon = "mobile"
campaign = "C24_WMDE_Mobile_DE_09"
description = "Based on VAR of C24_WMDE_Mobile_DE_08, VAR has 10 reasons pop-up."
campaign_tracking = "mob-de-09-ba-241118"
preview_link = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva"
preview_link_darkmode = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva&minervanightmode=1"
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&useskin=minerva&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

# Banners of the campaign, key after "banners" can be anything
[mobile.banners.ctrl]
filename = "./banners/mobile/C24_WMDE_Mobile_DE_09/banner_ctrl.ts"
pagename = "B24_WMDE_Mobile_DE_09_ctrl"
tracking = "org-mob09-241118-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/C24_WMDE_Mobile_DE_09/banner_var.ts"
pagename = "B24_WMDE_Mobile_DE_09_var"
tracking = "org-mob09-241118-var"

[mobile.test_matrix]
device = [ 'samsung_s10', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max"]
orientation = [ "portrait", "landscape"]


[pad]
name = "iPad"
icon = "pad"
campaign = "C24_WMDE_iPad_DE_01"
description = "Based on C24_WMDE_iPad_00"
campaign_tracking = "pad01-ba-241028"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&vectornightmode=1"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE"

[pad.banners.ctrl]
filename = "./banners/pad/C24_WMDE_iPad_DE_01/banner_ctrl.ts"
pagename = "B24_WMDE_iPad_DE_01_ctrl"
tracking = "org-pad01-241028-ctrl"

[pad.banners.var]
filename = "./banners/pad/C24_WMDE_iPad_DE_01/banner_var.ts"
pagename = "B24_WMDE_iPad_DE_01_var"
tracking = "org-pad01-241028-var"

[pad.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch' ]
orientation = [ "portrait", "landscape"]



[wpde_desktop]
name = "WPDE Desktop"
icon = "desktop"
campaign = "C24_WPDE_Desktop_01"
description = "Based on C23_WPDE_Desktop_02"
campaign_tracking = "wpde-01-241028"
preview_link = "/wpde-offline?devbanner={{banner}}"
# Until the banner server is live, we use the offline preview link
#preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_darkmode = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wpde_desktop.banners.ctrl]
filename = "./banners/wpde_desktop/C24_WPDE_Desktop_01/banner_ctrl.ts"
pagename = "B24_WPDE_Desktop_01_ctrl"
tracking = "wpde-01-241028-ctrl"

[wpde_desktop.banners.var]
filename = "./banners/wpde_desktop/C24_WPDE_Desktop_01/banner_var.ts"
pagename = "B24_WPDE_Desktop_01_var"
tracking = "wpde-01-241028-var"


[wpde_mobile]
name = "WPDE Mobile"
icon = "mobile"
campaign = "C24_WPDE_Mobile_01"
description = "Based on the control banner of last year's mobile-wpde-01"
campaign_tracking = "wpde-mob01-241028"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_darkmode = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wpde_mobile.banners.ctrl]
filename = "./banners/wpde_mobile/C24_WPDE_Mobile_01/banner_ctrl.ts"
pagename = "B24_WPDE_Mobile_01_ctrl"
tracking = "wpde-mob01-241028-ctrl"

[wpde_mobile.banners.var]
filename = "./banners/wpde_mobile/C24_WPDE_Mobile_01/banner_var.ts"
pagename = "B24_WPDE_Mobile_01_var"
tracking = "wpde-mob01-241028-var"



[english]
name = "English Desktop"
icon = "desktop"
campaign = "C24_WMDE_Desktop_EN_04"
description = "Based on CTRL desktop EN 03"
campaign_tracking = "en04-ba-241113"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype&vectornightmode=1"
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN"

[english.banners.ctrl]
filename = "./banners/english/C24_WMDE_Desktop_EN_04/banner_ctrl.ts"
pagename = "B24_WMDE_Desktop_EN_04_ctrl"
tracking = "org-en04-241113-ctrl"

[english.banners.var]
filename = "./banners/english/C24_WMDE_Desktop_EN_04/banner_var.ts"
pagename = "B24_WMDE_Desktop_EN_04_var"
tracking = "org-en04-241113-var"

[english.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]



[mobile_english]
name = "English Mobile"
icon = "mobile"
campaign = "C24_WMDE_Mobile_EN_01"
description = "Based on ctrl of C23_WMDE_Mobile_EN_02"
campaign_tracking = "mob_en01-ba-241028"
preview_link = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype"
preview_link_darkmode = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype&minervanightmode=1"
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode&useskin=minerva'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/C24_WMDE_Mobile_EN_01/banner_ctrl.ts"
pagename = "B24_WMDE_Mobile_EN_01_ctrl"
tracking = "org-mob_en01-241028-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/C24_WMDE_Mobile_EN_01/banner_var.ts"
pagename = "B24_WMDE_Mobile_EN_01_var"
tracking = "org-mob_en01-241028-var"

[mobile_english.test_matrix]
device = [ 'samsung_s10', 'nexus_6', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max" ]
orientation = [ "portrait", "landscape" ]

