# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
name = "Desktop"
icon = "desktop"
campaign = "C23_WMDE_Desktop_DE_05"
description = "CTRL as base, VAR points to a new version of the address form on spenden"
campaign_tracking = "05-ba-230918"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/banner_ctrl.ts"
pagename = "B23_WMDE_Desktop_DE_05_ctrl"
tracking = "org-05-230918-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/banner_var.ts"
pagename = "B23_WMDE_Desktop_DE_05_var"
tracking = "org-05-230918-var"

[desktop.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]


[mobile]
name = "Mobile"
icon = "mobile"
campaign = "C23_WMDE_Mobile_DE_03"
description = "VAR has payment type icon buttons"
campaign_tracking = "mob-de-03-ba-230821"
preview_link = "/mobile/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype&useskin=minerva"
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&useskin=minerva&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

# Banners of the campaign, key after "banners" can be anything
[mobile.banners.ctrl]
filename = "./banners/mobile/banner_ctrl.ts"
pagename = "B23_WMDE_Mobile_DE_03_ctrl"
tracking = "org-mob03-230821-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/banner_var.ts"
pagename = "B23_WMDE_Mobile_DE_03_var"
tracking = "org-mob03-230821-var"

[mobile.test_matrix]
device = [ 'samsung_s10', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max"]
orientation = [ "portrait", "landscape"]


[pad]
name = "iPad"
icon = "pad"
campaign = "C23_WMDE_iPad_00"
description = "VAR has a header text above the slider"
campaign_tracking = "pad00-ba-230426"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE"

[pad.banners.ctrl]
filename = "./banners/pad/banner_ctrl.ts"
pagename = "B23_WMDE_iPad_00_ctrl"
tracking = "org-pad00-230501-ctrl"

[pad.banners.var]
filename = "./banners/pad/banner_var.ts"
pagename = "B23_WMDE_iPad_00_var"
tracking = "org-pad00-230501-var"

[pad.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch' ]
orientation = [ "portrait", "landscape"]



[wikipediade]
name = "WPDE Desktop"
icon = "desktop"
campaign = "C23_WPDE_Desktop_00"
description = "Nothing to see here"
campaign_tracking = "wpde-00-230501"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade.banners.ctrl]
filename = "./banners/wpde_desktop/banner_ctrl.ts"
pagename = "B23_WPDE_Desktop_00_ctrl"
tracking = "wpde-00-230501-ctrl"



[wikipediade_mobile]
name = "WPDE Mobile"
icon = "mobile"
campaign = "C23_WPDE_Mobile_00"
description = "Nothing to see here"
campaign_tracking = "wpde-mob00-230501"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wikipediade_mobile.banners.ctrl]
filename = "./banners/wpde_mobile/banner_ctrl.ts"
pagename = "B23_WPDE_Mobile_00_ctrl"
tracking = "wpde-mob00-230501-ctrl"



[english]
name = "English Desktop"
icon = "desktop"
campaign = "C23_WMDE_Desktop_EN_00"
description = "VAR has the already donated modal"
campaign_tracking = "en00-ba-230421"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[english.banners.ctrl]
filename = "./banners/english/banner_ctrl.ts"
pagename = "B23_WMDE_Desktop_EN_00_ctrl"
tracking = "org-en00-230421-ctrl"

[english.banners.var]
filename = "./banners/english/banner_var.ts"
pagename = "B23_WMDE_Desktop_EN_00_var"
tracking = "org-en00-230421-var"

[english.test_matrix]
platform = ["edge", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
resolution = ["800x600", "1024x768", "1280x960", "1600x1200", "1920x1200", "2560x1440"]



[mobile_english]
name = "English Mobile"
icon = "mobile"
campaign = "C23_WMDE_Mobile_EN_00"
description = "Tab button VS interior button on mini banners"
campaign_tracking = "mob_en00-ba-230425"
preview_link = "/en-mobile/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B22_WMDE_local_prototype"
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode&useskin=minerva'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/banner_ctrl.ts"
pagename = "B23_WMDE_Mobile_EN_00_ctrl"
tracking = "org-mob_en00-230501-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/banner_var.ts"
pagename = "B23_WMDE_Mobile_EN_00_var"
tracking = "org-mob_en00-230501-var"

[mobile_english.test_matrix]
device = [ 'samsung_s10', 'nexus_6', 'iphone_xs_max', 'iphone_5s', 'iphone_se', "iphone_8", "iphone_12_mini", "iphone_7_plus", "iphone_11_pro_max" ]
orientation = [ "portrait", "landscape" ]


[pad_en]
name = "English iPad"
icon = "pad"
campaign = "C23_WMDE_iPad_EN_00"
description = "VAR has soft close"
campaign_tracking = "en-ipad00-230426"
preview_link ='/wiki/Main_Page?devbanner={{banner}}&banner=B22_WMDE_local_prototype'
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN"

[pad_en.banners.ctrl]
filename = "./banners/pad_english/banner_ctrl.ts"
pagename = "B23_WMDE_iPad_EN_00_ctrl"
tracking = "org-en-ipad00-230501-ctrl"

[pad_en.banners.var]
filename = "./banners/pad_english/banner_var.ts"
pagename = "B23_WMDE_iPad_EN_00_var"
tracking = "org-en-ipad00-230501-var"

[pad_en.test_matrix]
device = [ 'ipad_mini', 'ipad', 'ipad_pro_9_7_inch', 'ipad_pro_12_inch']
orientation = [ "portrait", "landscape"]
